# Generated by Django 6.0.6 on 2026-07-02 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('highest_qualification', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('experience_years', models.DecimalField(decimal_places=1, max_digits=4)),
                ('current_organization', models.CharField(blank=True, max_length=200)),
                ('current_designation', models.CharField(blank=True, max_length=200)),
                ('skills', models.TextField(help_text='Comma-separated skills')),
                ('publications', models.IntegerField(default=0)),
                ('research_papers', models.TextField(blank=True, help_text='List of research papers')),
                ('patents', models.IntegerField(default=0)),
                ('google_scholar_link', models.URLField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('resume', models.FileField(upload_to='candidates/resumes/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='candidates/photos/')),
                ('cover_letter', models.TextField(blank=True)),
                ('ai_ats_score', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('skills_match_score', models.FloatField(default=0)),
                ('experience_match_score', models.FloatField(default=0)),
                ('education_match_score', models.FloatField(default=0)),
                ('research_score', models.FloatField(default=0)),
                ('ai_analysis', models.JSONField(blank=True, default=dict)),
                ('strength_weakness', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('ai_reviewed', 'AI Reviewed'), ('shortlisted', 'Shortlisted'), ('interview_scheduled', 'Interview Scheduled'), ('interviewed', 'Interviewed'), ('evaluated', 'Evaluated'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('offered', 'Offered'), ('joined', 'Joined')], default='applied', max_length=50)),
                ('applied_date', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='jobs.job')),
            ],
            options={
                'ordering': ['-ai_ats_score', '-applied_date'],
            },
        ),
    ]
