# Generated by Django 6.0.6 on 2026-07-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('hod', 'Head of Department'), ('dean', 'Dean'), ('director', 'Director')], max_length=50)),
                ('department', models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('ece', 'Electronics & Communication'), ('eee', 'Electrical & Electronics'), ('mech', 'Mechanical Engineering'), ('civil', 'Civil Engineering'), ('it', 'Information Technology'), ('mca', 'MCA'), ('mba', 'MBA')], max_length=50)),
                ('specialization', models.CharField(max_length=200)),
                ('qualifications', models.TextField()),
                ('min_experience', models.IntegerField()),
                ('max_experience', models.IntegerField()),
                ('required_skills', models.TextField(help_text='Comma-separated required skills')),
                ('description', models.TextField()),
                ('responsibilities', models.TextField()),
                ('vacancies', models.IntegerField()),
                ('salary_range', models.CharField(max_length=100)),
                ('application_start_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
