# Generated by Django 6.0.6 on 2026-07-02 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('members', models.ManyToManyField(related_name='panel_members', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_type', models.CharField(choices=[('technical', 'Technical Interview'), ('hr', 'HR Interview'), ('panel', 'Panel Interview'), ('director', 'Director Round')], max_length=50)),
                ('scheduled_date', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=60)),
                ('venue', models.CharField(max_length=200)),
                ('meeting_link', models.URLField(blank=True, help_text='For online interviews')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=50)),
                ('panel_score', models.FloatField(blank=True, null=True)),
                ('panel_feedback', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, max_length=100)),
                ('email_sent', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='candidates.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='jobs.job')),
                ('panelists', models.ManyToManyField(related_name='interviews', to=settings.AUTH_USER_MODEL)),
                ('panel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interviews.interviewpanel')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
    ]
